### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by manavo** [vivekn/sentiment#14]
Not sure if it was taken down on purpose, but http://sentiment.vivekn.com isn't loading anymore.

**Comment by Rahul-Raviprasad** [comment]
I too tried. Can't reach.

**Comment by RobErskine** [comment]
Hey there. Just wanted to +1 this. My bot stopped working because of the demo being down. Lemme know how I can help!

**Comment by manavo** [comment]
Looks like the [web interface is here](https://github.com/vivekn/sentiment-web), so you could run an instance of it yourself (I might try and do this if I get a chance)

**Comment by manavo** [comment]
There are other issues for the same issue, no point having multiple open at the same time. So closing this now.
